project:
  type: book

book:
  google-analytics: "G-KMNNS24XZ5"
  title: "Translational Bioinformatics for Immunogenomics"
  reader-mode: true
  page-footer:
    left: |
      Translational Bioinformatics for Immunogenomics was written by Matthew S. Krantz
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  sidebar:
    collapse-level: 1
  site-url: https://tb4i.mattkrantz.com/
  repo-url: https://github.com/mattkrantz/tb4i/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - part: hla.qmd
      chapters: 
        - functional-divergence.qmd
        - hla-imputation-programs.qmd
        - hla-analysis-programs.qmd
    - part: kir.qmd
      chapters:
        - kir-imputation-programs.qmd
    - part: erap.qmd
      chapters:
        - erap-imputation.qmd
    - bonus.qmd
    - part: drug-allergy.qmd
      chapters:
        - immediate-drug-allergy.qmd
        - delayed-drug-allergy.qmd
        - specific-drugs.qmd
    - part: bioinformatic-best-practices.qmd
      chapters:
        - reproducible-data-analysis-workflow.qmd
        - project-organization.qmd
        - file-naming-conventions.qmd
        - package-managers.qmd
        - version-control-with-git.qmd
        - rmarkdown.qmd
        - make.qmd
        - docker.qmd
    - genotype-imputation.qmd
    - presenting-your-medical-research.qmd
    - on-being-a-physician-scientist.qmd
    - references.qmd
    
bibliography: references.bib
  
number-sections: true

number-depth: 1
    
toc-depth: 4

resources:
  - CNAME
  
callout:
  font-size: 2em

format:
  html:
    theme: cosmo
    css: styles.css
editor: visual

